version: "3"
services:
  api:
    build: .
    volumes:
      - ./:/usr/src/app:ro
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password1234
      - DATABASE_NAME=StudentDatabase
      - DATABASE_USERNAME=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password1234
      - POSTGRES_DB=StudentDatabase
    
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: